# Generated by Django 3.0.6 on 2020-06-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulas',
            name='Capacidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cursadas',
            name='CantidadAlumnos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cursadas',
            name='Carrera',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cursadas',
            name='NombredeMateria',
            field=models.CharField(max_length=40),
        ),
    ]
