# Generated by Django 3.0.7 on 2020-06-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='materia',
            fields=[
                ('idMateria', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('NombredeMateria', models.CharField(max_length=45)),
                ('Carrera', models.CharField(max_length=45)),
            ],
        ),
    ]
