# Generated by Django 3.0.7 on 2020-06-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aula',
            fields=[
                ('nroAula', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('piso', models.CharField(max_length=2)),
                ('capacidad', models.IntegerField()),
            ],
        ),
    ]
