# Generated by Django 3.0.7 on 2020-06-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comision', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comision',
            old_name='idTurno',
            new_name='turno',
        ),
        migrations.AddField(
            model_name='comision',
            name='comision',
            field=models.CharField(choices=[('1A', 'Comision_1A'), ('1B', 'Comision_1B'), ('2A', 'Comision_2A'), ('2B', 'Comision_2B'), ('3A', 'Comision_3A'), ('3B', 'Comision_3B'), ('4A', 'Comision_4A'), ('4B', 'Comision_4B')], default='1A', max_length=2),
        ),
        migrations.AddField(
            model_name='turno',
            name='turno',
            field=models.CharField(choices=[('T', 'Tarde: 13:00 a 19:00'), ('N', 'Noche: 19:00 a 23:00')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='comision',
            name='idComision',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='turno',
            name='idTurno',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
