# Generated by Django 3.0.7 on 2020-06-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comision', '0002_auto_20200620_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision',
            name='comision',
        ),
        migrations.AlterField(
            model_name='comision',
            name='idComision',
            field=models.CharField(choices=[('1A', 'Comision_1A'), ('1B', 'Comision_1B'), ('2A', 'Comision_2A'), ('2B', 'Comision_2B'), ('3A', 'Comision_3A'), ('3B', 'Comision_3B'), ('4A', 'Comision_4A'), ('4B', 'Comision_4B')], default='1A', max_length=2, primary_key=True, serialize=False),
        ),
    ]
