# Generated by Django 3.0.7 on 2020-06-20 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asignar', '0002_remove_comisionmateria_idcomision'),
        ('aula', '0001_initial'),
        ('comision', '0003_auto_20200620_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='comisionN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision', models.CharField(choices=[('1A', 'Comision_1A'), ('1B', 'Comision_1B'), ('2A', 'Comision_2A'), ('2B', 'Comision_2B'), ('3A', 'Comision_3A'), ('3B', 'Comision_3B'), ('4A', 'Comision_4A'), ('4B', 'Comision_4B')], default='1A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='turnoN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('T', 'Tarde: 13:00 a 19:00'), ('N', 'Noche: 19:00 a 23:00')], default='N', max_length=1)),
                ('NroAula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aula.aula')),
            ],
        ),
        migrations.RemoveField(
            model_name='turno',
            name='NroAula',
        ),
        migrations.DeleteModel(
            name='comision',
        ),
        migrations.DeleteModel(
            name='turno',
        ),
        migrations.AddField(
            model_name='comisionn',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comision.turnoN'),
        ),
    ]
