# Generated by Django 3.0.7 on 2020-06-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cursada',
            fields=[
                ('idCursada', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('cantidadAlumnos', models.IntegerField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.materia')),
            ],
        ),
    ]
