# Generated by Django 3.0.7 on 2020-06-18 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NroAula', models.CharField(max_length=2)),
                ('Piso', models.CharField(max_length=2)),
                ('Capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cursadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombredeMateria', models.CharField(max_length=45)),
                ('Carrera', models.CharField(max_length=45)),
                ('CantidadAlumnos', models.IntegerField()),
                ('Comision', models.CharField(choices=[('A', 'Comision A'), ('B', 'Comision B')], default='A', max_length=1)),
                ('Turno', models.CharField(choices=[('T', 'Tarde'), ('N', 'Noche')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aulas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.Aulas')),
                ('Cursadas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.Cursadas')),
            ],
        ),
    ]
