# Generated by Django 3.0.7 on 2020-06-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comision', '0001_initial'),
        ('cursada', '0001_initial'),
        ('aula', '0001_initial'),
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cursadaAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCursada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cursada.cursada')),
                ('nroAula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aula.aula')),
            ],
        ),
        migrations.CreateModel(
            name='comisionMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lun', 'Lunes'), ('Mar', 'Martes'), ('Mie', 'Miércoles'), ('Jue', 'Jueves'), ('Vie', 'Viernes')], default='Lun', max_length=3)),
                ('NombredeMateria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='materia.materia')),
                ('idComision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comision.comision')),
            ],
        ),
    ]
