# Generated by Django 3.0.7 on 2020-06-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comisionmateria',
            name='idComision',
        ),
    ]
