# Generated by Django 3.0.7 on 2020-06-20 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comision', '0004_auto_20200620_1619'),
        ('asignar', '0002_remove_comisionmateria_idcomision'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionmateria',
            name='comision',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='comision.comisionN'),
        ),
    ]
