# Generated by Django 3.0.6 on 2020-06-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NroAula', models.CharField(max_length=2)),
                ('Piso', models.CharField(max_length=2)),
                ('Capacidad', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Cursadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombredeMateria', models.CharField(max_length=35)),
                ('Carrera', models.CharField(max_length=35)),
                ('CantidadAlumnos', models.CharField(max_length=2)),
                ('Turno', models.CharField(choices=[('T', 'Tarde'), ('N', 'Noche')], default='N', max_length=1)),
            ],
        ),
    ]
