# Generated by Django 3.0.6 on 2020-06-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_auto_20200613_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursadas',
            name='Comision',
            field=models.CharField(choices=[('A', 'Comision A'), ('B', 'Comision B')], default='A', max_length=1),
        ),
    ]
