# Generated by Django 3.0.7 on 2020-06-18 04:58

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='Aulas',
            fields=[
            ],
        ),
        migrations.CreateModel(
            name='Cursadas',
            fields=[
            ],
        ),
    ]
